[package]
name = "dez80_cli"
version = "1.0.0"
description = "A Z80 disassembler interface based on the DeZ80 library."
repository = "https://github.com/rzumer/rz80"
authors = ["Raphaël Zumer <rzumer@tebako.net>"]
license = "MIT"
edition = "2018"

[features]
default = ["rayon"]

[dependencies]
clap = "2.33"
rayon = { version = "1.1", optional = true }
dez80 = { version = "0.1", path = "../" }
