[package]
name = "rz80_cli"
version = "0.1.0"
authors = ["Raphaël Zumer <rzumer@tebako.net>"]
edition = "2018"

[features]
default = ["rayon"]

[dependencies]
clap = "2.33"
rayon = { version = "1.1", optional = true }
rz80 = { version = "0.1", path = "../" }
