[package]
name = "dez80_cli"
version = "1.0.2"
description = "A Z80 disassembler interface based on the DeZ80 library."
repository = "https://github.com/rzumer/dez80"
authors = ["Raphaël Zumer <rzumer@tebako.net>"]
license = "MIT"
edition = "2021"

[features]
default = ["rayon"]

[dependencies]
clap = { version = "4.4", features = ["cargo"] }
rayon = { version = "1.8", optional = true }
dez80 = { path = "../" }
