language: rust
matrix:
  include:
    - name: "DeZ80"
      env: cd $TRAVIS_BUILD_DIR/
    - name: "DeZ80 CLI"
      env: cd $TRAVIS_BUILD_DIR/bin/
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build
  - cargo test
  - cargo bench --no-run
