[package]
name = "rz80"
version = "0.1.0"
description = "A Z80 disassembly library."
repository = "https://github.com/rzumer/rz80"
authors = ["Raphaël Zumer <rzumer@tebako.net>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.2"
rayon = "1.1"

[[bench]]
name = "bench"
harness = false
