[package]
name = "hachiya"
version = "0.1.0"
authors = ["Raphaël Zumer <rzumer@tebako.net>"]
edition = "2018"

[dependencies]
rayon = "1.1"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "cpu"
harness = false
