[package]
name = "dez80"
version = "1.0.0"
description = "A Z80 disassembly library."
repository = "https://github.com/rzumer/dez80"
authors = ["Raphaël Zumer <rzumer@tebako.net>"]
license = "MIT"
edition = "2018"

[dependencies]
strum = "0.15.0"
strum_macros = "0.15.0"

[dev-dependencies]
criterion = "0.2"
rayon = "1.1"

[[bench]]
name = "bench"
harness = false
