name: DeZ80

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Validate dependency tree licenses
      uses: EmbarkStudios/cargo-deny-action@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build benchmarks
      run: cargo bench --no-run
    - name: Run rustfmt
      run: |
        rustup component add rustfmt \
        && cargo fmt -- --check
    - name: Run Clippy
      run: |
        rustup component add clippy \
        && cargo clippy
